name: render report

on:
  push:
    branches: main

jobs:
  render:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: render Report
        run: Rscript -e 'rmarkdown::render("./code/projectrmarkdown.Rmd", output_format = "html_document")'

      - name: commit rendered Report
        run: |
          mv ./code/projectrmarkdown.html index.html
          mv index.html docs
          git add docs/index.html
          git commit -m "rebuild projectrmarkdown.Rmd" || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
